"""Shared database model constants."""

EMAIL_MAX_LENGTH = 320
FILE_EXTENSION_MAX_LENGTH = 20
FILENAME_MAX_LENGTH = 255
FULL_NAME_MAX_LENGTH = 150
PASSWORD_HASH_MAX_LENGTH = 255
TITLE_MAX_LENGTH = 255
ASSIGNEE_MAX_LENGTH = 150
